config/routes.rb
Rails.application.routes.draw do
  get 'payments/check/:id', to: "payments#check", as: :pay_check
  patch 'payments/update_check', to: "payments#update_check", as: :update_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root "home#index"
  get "/bettercheck", to: "home#bettercheck"
  namespace :admin do
    get "/dashboard", to: "dashboard#index", as: :dashboard
    get "/generate_check", to: "checks#generate_check", as: :generate_check, defaults: { format: 'pdf' }
    get "/change_password", to: "passwords#change_password", as: :change_password
    patch "/update_password", to: "passwords#update_password", as: :update_password
    resources :checks do
      collection do
        post "/search_check", to: "checks#search_check"
        get "/payment_link", to: "checks#payment_link"
        post "/create_payment_link", to: "checks#create_payment_link"
      end
    end
    get "/reports", to: "reports#index", as: :reports
    resources :subscriptions
  end
end

app/views/layouts/adminside/_footer.html.erb
<div class="footer text-muted">
	&copy; 2017. <a href="#">Cardless PayTech</a><br />
	<!-- Powered by <a href="http://complitech.us" target="_blank">Complitech Inc.</a> -->
</div>

app/views/layouts/adminside/_header.html.erb
<!-- Main navbar -->
<div class="navbar navbar-inverse">
	<div class="navbar-header">
		<a class="navbar-brand" href="index.html"><%= image_tag "CP-logo/cp-209.png", alt: "" %></a>

		<ul class="nav navbar-nav pull-right visible-xs-block">
			<li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
		</ul>
	</div>

	<div class="navbar-collapse collapse" id="navbar-mobile">
		<ul class="nav navbar-nav navbar-right">

			<li class="dropdown dropdown-user">
				<a class="dropdown-toggle" data-toggle="dropdown">
					<%= image_tag "admin/placeholder.jpg", alt: "" %>
					<span><%= current_user.business_name %></span>
					<i class="caret"></i>
				</a>

				<ul class="dropdown-menu dropdown-menu-right">
					<li><a href="#"><i class="icon-user-plus"></i> My Account</a></li>
					<li><a href="<%= admin_change_password_path %>"><i class="icon-coins"></i> Change Password</a></li>
					<li class="divider"></li>
					<li><a href="<%= destroy_user_session_path %>" data-method="delete"><i class="icon-switch2"></i> Logout</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<!-- /main navbar -->


<!-- Second navbar -->
<div class="navbar navbar-default" id="navbar-second">
	<ul class="nav navbar-nav no-border visible-xs-block">
		<li><a class="text-center collapsed" data-toggle="collapse" data-target="#navbar-second-toggle"><i class="icon-menu7"></i></a></li>
	</ul>

	<div class="navbar-collapse collapse" id="navbar-second-toggle">
		<% if current_user.is_account_info_provided? %>
			<ul class="nav navbar-nav">
				<li class="<%= active_class(admin_dashboard_path) %>"><a href="<%= admin_dashboard_path %>"><i class="icon-display4 position-left"></i> Dashboard</a></li>

				<li class="<%= active_class('') %>">
					<a href="#" class="dropdown-toggle"><i class="fa fa-info-circle position-left"></i> How it works </a>
				</li>

				<li class="<%= active_class(new_admin_check_path) %>">
					<a href="<%= new_admin_check_path %>" class="dropdown-toggle"><i class="fa fa-check-circle-o position-left"></i> Input Check </a>
				</li>

				<li class="<%= active_class(admin_checks_path) %>">
					<a href="<%= admin_checks_path %>" class="dropdown-toggle">
						<i class="fa fa-print position-left"></i> Print Check 
					</a>
				</li>

				<li class="<%= active_class(payment_link_admin_checks_path) %>">
					<a href="<%= payment_link_admin_checks_path %>" class="dropdown-toggle">
						<i class="fa fa-newspaper-o position-left"></i> Generate Invoice Link </span>
					</a>
				</li>

				<li class="<%= active_class(admin_reports_path) %>">
					<a href="<%= admin_reports_path %>" class="dropdown-toggle">
						<i class="fa fa-stack-exchange position-left"></i> Reports </span>
					</a>
				</li>
			</ul>
		<% end %>

		<ul class="nav navbar-nav navbar-right">
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<i class="icon-cog3"></i>
					<span class="visible-xs-inline-block position-right">Share</span>
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu dropdown-menu-right">
					<li><a href="<%= admin_subscriptions_path %>"><i class="icon-statistics"></i> Subscriptions</a></li>
					<li class="divider"></li>
					<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<!-- /second navbar -->