config/routes.rb
Rails.application.routes.draw do
  get 'payments/check/:id', to: "payments#check", as: :pay_check
  patch 'payments/update_check', to: "payments#update_check", as: :update_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root "home#index"
  get "/bettercheck", to: "home#bettercheck"
  namespace :admin do
    get "/dashboard", to: "dashboard#index", as: :dashboard
    get "/generate_check", to: "checks#generate_check", as: :generate_check, defaults: { format: 'pdf' }
    get "/change_password", to: "passwords#change_password", as: :change_password
    patch "/update_password", to: "passwords#update_password", as: :update_password
    resources :checks do
      collection do
        post "/search_check", to: "checks#search_check"
        get "/payment_link", to: "checks#payment_link"
        post "/create_payment_link", to: "checks#create_payment_link"
      end
    end
    get "/reports", to: "reports#index", as: :reports
    resources :subscriptions
  end
end

app/models/check.rb
class Check < ActiveRecord::Base
	# Filters
	after_create :generate_unique_token

  # Validations
  validates :amount, :pay_to_the_order_of, :date, :memo1, presence: true

	# Associations
  belongs_to :user

  # Constants
  MONTHS = {1 => "Jan", 2 => "Feb", 3 => "Mar", 4 => "Apr", 5 => "May", 6 => "Jun", 7 => "Jul", 8 => "Aug", 9 => "Sep", 10 => "Oct", 11 => "Nov", 12 => "Dec"}

  private
  def generate_unique_token
  	token = SecureRandom.hex(20)
  	self.update_attributes(unique_code: token)
  end
end

app/controllers/admin/checks_controller.rb
class Admin::ChecksController < Admin::BaseController
  before_filter :set_check, only: [:edit, :update, :show, :delete]

  # GET /admin/checks
  def index
    @checks = current_user.checks
  end

  # GET /admin/checks/new
  def new
    @check = Check.new
  end

  # POST /admin/checks
  def create
    @check = current_user.checks.build(check_params)
    if @check.save
      redirect_to admin_checks_path, notice: "New check has been created."
    else
      render :new, alert: @check.errors.full_messages
    end
  end

  # GET /admin/checks/:id/edit
  def edit
  end

  # PATCH /admin/checks/:id
  def update
    @check.update(check_params)
    if @check.save
      redirect_to admin_checks_path, notice: "Check has been updated."
    else
      render :edit, alert: @check.errors.full_messages
    end
  end

  # GET /admin/checks/:id
  def show
  end

  # DELETE /admin/checks/:id
  def delete
  end

  # GET /admin/checks/search_check as JS
  def search_check
    month = params[:month]
    from_date = params[:from_date]
    to_date = params[:to_date]

    if month != ""
      @checks = Check.where("extract(month from date) = ?", month)
    elsif from_date != "" and to_date != ""
      @checks = Check.where("date > ? and date < ?", from_date, to_date)
    end
  end

  # GET /admin/checks/payment_link
  def payment_link
  end

  # GET /admin/checks/create_payment_link
  def create_payment_link
    @check = current_user.checks.build(amount: params[:amount].to_f, transaction_fee: params[:transaction_fee], memo1: params[:memo], pay_to_the_order_of: params[:pay_to], date: DateTime.now)
    unless @check.save
      puts @check.errors.full_messages
    end
  end

  # GET Create PDF as PDF
  def generate_check
    @ids = eval(params[:id])
    @checks = Check.find(@ids)
    respond_to do |format|
      format.pdf do
        render :pdf => "checks", template: "admin/checks/generate_check.pdf.erb", layout: "pdf.html.erb", page_size: "Letter"
      end
    end
  end

  private
  # Strong Parameters for check
  def check_params
    params.require(:check).permit(:account_holder_name, :street_address, :city, :state, :zip, :date, :check_number, :pay_to_the_order_of, :amount, :memo1, :memo2, :routing_number, :checking_account_number)
  end

  def payment_link_params
    params.require(:check).permit(:amount, :transaction_fee, :memo1, :pay_to_the_order_of)
  end

  # Before Filter Callback method
  def set_check
    @check = Check.find(params[:id])
  end
end

app/helpers/admin/checks_helper.rb
module Admin::ChecksHelper
end

app/views/admin/checks/_check_list.html.erb
<table class="table check_datatable">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Date</th>
			<th>Memo1</th>
			<th>Name</th>
			<th>Company</th>
			<th>Amount</th>
			<th class="text-center">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @checks.each do |check| %>
		<tr>
			<td><%= check_box_tag "check_id", check.id, false,id: "check_#{check.id}", class: "check_id" %></td>
			<td><%= check.date %></td>
			<td><%= check.memo1 %></td>
			<td><%= check.account_holder_name %></td>
			<td><%= check.pay_to_the_order_of %></td>
			<td><%= number_to_currency(check.amount, precision: 2) %></td>
			<!-- <td><span class="label label-success">Active</span></td> -->
			<td class="text-center">
				<ul class="icons-list">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-menu9"></i>
						</a>

						<ul class="dropdown-menu dropdown-menu-right">
							<li><a href="<%= edit_admin_check_path(check) %>"><i class="icon-pencil"></i> Edit</a></li>
							<li><%= link_to "Print", admin_generate_check_path(id: check.id), target: "_blank" %></li>
							<li><a href="<%= admin_check_path(check) %>" data-confirm="Are you sure you want to delete this record?" data-method="delete"><i class="icon-trash"></i> Delete</a></li>
						</ul>
					</li>
				</ul>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= form_tag admin_generate_check_path, method: :get, id: "form_print_checks" do %>
	<%= hidden_field_tag "id", "",id: "form_check_id" %>
<% end %>

<script type="text/javascript">

	$(".check_datatable").DataTable({
    "order": [],
    "displayStart": 0,
    "columnDefs": [ {
      "targets": [0, 6],
      "orderable": false,
    } ],
    dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
    language: {
      search: '<span>Filter:</span> _INPUT_',
      lengthMenu: '<span>Show:</span> _MENU_',
      paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
    },
    drawCallback: function () {
      $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
    },
    preDrawCallback: function() {
      $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
    }
  });

  $('.dataTables_filter input[type=search]').attr('placeholder','Type to filter...');

  $('.dataTables_length select').select2({
    minimumResultsForSearch: Infinity,
    width: 'auto'
  });

	$(".check_id").click(function(){
		var value = [];
		if($("#form_check_id").val() != ""){
			value = $("#form_check_id").val();
			value = JSON.parse(value);
			console.log("In IF");
		}
		if(this.checked == true)
		{
			value.push(this.value);
			$("#form_check_id").val(JSON.stringify(value));
		}
		else
		{
			alert("Clicked Not");
		}
	});
</script>

app/views/admin/checks/_form.html.erb
<%= form_for([:admin,@check], html: { class: "form-horizontal check_form_validator" }) do |f| %>
  <fieldset class="content-group">
    <div class="row">
      <div class="form-group">
        <div class="col-md-4">
          <%= f.text_field :account_holder_name, autofocus: true, class: "form-control", placeholder: "Account Holder's Name", :data => { 'ng-model' => "check.account_holder_name" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :street_address, autofocus: true, class: "form-control", placeholder: "Street Address", :data => { 'ng-model' => "check.street_address" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :city, autofocus: true, class: "form-control", placeholder: "City", :data => { 'ng-model' => "check.city" } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <div class="col-md-4">
          <%= f.text_field :state, autofocus: true, class: "form-control", placeholder: "State", :data => { 'ng-model' => "check.state" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :zip, autofocus: true, class: "form-control", placeholder: "Zip Code", :data => { 'ng-model' => "check.zip" } %>
        </div>
        <div class="col-md-4">
          <div class="input-group">
            <span class="input-group-addon"><i class="icon-calendar"></i></span>
            <%= f.text_field :date, autofocus: true, class: "form-control datepicker", placeholder: "Enter Date", :data => { 'ng-model' => "check.date" } %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <div class="col-md-4">
          <%= f.text_field :check_number, autofocus: true, class: "form-control", placeholder: "Checking Number", :data => { 'ng-model' => "check.check_number" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :pay_to_the_order_of, autofocus: true, class: "form-control", placeholder: "Pay to the Order of", :data => { 'ng-model' => "check.pay_to" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :amount, autofocus: true, class: "form-control", placeholder: "Enter Amount", :data => { 'ng-model' => "check.amount" } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <div class="col-md-4">
          <%= f.text_field :memo1, autofocus: true, class: "form-control", placeholder: "Memo1", :data => { 'ng-model' => "check.memo1" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :memo2, autofocus: true, class: "form-control", placeholder: "Memo2", :data => { 'ng-model' => "check.memo2" } %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :routing_number, autofocus: true, class: "form-control", placeholder: "Routing Number", :data => { 'ng-model' => "check.routing" } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <div class="col-md-4">
          <%= f.text_field :checking_account_number, autofocus: true, class: "form-control", placeholder: "Checking Account Number", :data => { 'ng-model' => "check.check_account" } %>
        </div>

        <div class="col-md-4">
        </div>

        <div class="col-md-4 text-right">
          <% if f.object.new_record? %>
            <%= f.submit "Create", class: "btn btn-primary" %>
          <% else %>
            <%= f.submit "Update", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </fieldset>
<% end %>

<script type="text/javascript">
  
var check_form_validator = $(".check_form_validator").validate({
        ignore: 'input[type=hidden], .select2-search__field', // ignore hidden fields
        errorClass: 'validation-error-label',
        successClass: 'validation-valid-label',
        highlight: function(element, errorClass) {
            $(element).removeClass(errorClass);
        },
        unhighlight: function(element, errorClass) {
            $(element).removeClass(errorClass);
        },

        // Different components require proper error label placement
        errorPlacement: function(error, element) {

            // Styled checkboxes, radios, bootstrap switch
            if (element.parents('div').hasClass("checker") || element.parents('div').hasClass("choice") || element.parent().hasClass('bootstrap-switch-container') ) {
                if(element.parents('label').hasClass('checkbox-inline') || element.parents('label').hasClass('radio-inline')) {
                    error.appendTo( element.parent().parent().parent().parent() );
                }
                 else {
                    error.appendTo( element.parent().parent().parent().parent().parent() );
                }
            }

            // Unstyled checkboxes, radios
            else if (element.parents('div').hasClass('checkbox') || element.parents('div').hasClass('radio')) {
                error.appendTo( element.parent().parent().parent() );
            }

            // Input with icons and Select2
            else if (element.parents('div').hasClass('has-feedback') || element.hasClass('select2-hidden-accessible')) {
                error.appendTo( element.parent() );
            }

            // Inline checkboxes, radios
            else if (element.parents('label').hasClass('checkbox-inline') || element.parents('label').hasClass('radio-inline')) {
                error.appendTo( element.parent().parent() );
            }

            // Input group, styled file input
            else if (element.parent().hasClass('uploader') || element.parents().hasClass('input-group')) {
                error.appendTo( element.parent().parent() );
            }

            else {
                error.insertAfter(element);
            }
        },
        validClass: "validation-valid-label",
        rules: {
          "check[account_holder_name]": {
            required: true,
          },
          "check[street_address]": {
            required: true,
          },
          "check[city]": {
            required: true,
          },
          "check[state]": {
            required: true,
          },
          "check[zip]": {
            required: true,
            digits: true,
            minlength: 5,
            maxlength: 6,
          },
          "check[date]": {
            required: true,
          },
          "check[check_number]": {
            required: true,
            digits: true,
          },
          "check[pay_to_the_order_of]": {
            required: true,
          },
          "check[amount]": {
            required: true,
            number: true,
          },
          "check[routing_number]": {
            required: true,
          },
          "check[checking_account_number]": {
            required: true,
          },
        },
        messages: {
          "check[account_holder_name]": {
            required: "Account holder name is required.",
          },
          "check[street_address]": {
            required: "Street address is required.",
          },
          "check[city]": {
            required: "City is required.",
          },
          "check[state]": {
            required: "State is required.",
          },
          "check[zip]": {
            required: "Zipcode is required.",
          },
          "check[date]": {
            required: "Date is required.",
          },
          "check[check_number]": {
            required: "Check number is required.",
          },
          "check[pay_to_the_order_of]": {
            required: "This field is required.",
          },
          "check[amount]": {
            required: "Amount is required.",
          },
          "check[routing_number]": {
            required: "Routing number is required.",
          },
          "check[checking_account_number]": {
            required: "Account number is required.",
          },
        }
    });

  $(".datepicker").datetimepicker({      
    format: 'MM-DD-YYYY',     
    //minDate : moment().millisecond(0).second(0).minute(0).hour(0),      
  });
</script>

app/views/admin/checks/_search_checks_form.html.erb
<%= form_tag search_check_admin_checks_path, remote: true, class: "form-horizontal" do %>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-3">
				<div class="form-group">
			    <%= label_tag "Month" %>
			    <%= select_tag "month", options_from_collection_for_select(Check::MONTHS, :first, :last), style: "width: 150px;", :include_blank => "--Select Month--" ,autofocus: true, class: "form-control" %>
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<%= label_tag "From Date" %>
    			<%= text_field_tag "from_date", "",style: "width: 150px;", autofocus: true, class: "form-control from_date" %>
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<%= label_tag "To Date" %>
    			<%= text_field_tag "to_date", "",style: "width: 150px;", autofocus: true, class: "form-control to_date" %>
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<%= submit_tag "Search", class: "btn btn-primary" %>
				</div>
			</div>
    </div>
  </div>
<% end %>
<div class="form-group">
	<%= link_to "Print Selected", "#", class: "btn btn-primary button_print", target: "_blank" %>
</div>
<script type="text/javascript">
	$(".from_date").datetimepicker({      
	    format: 'MM-DD-YYYY',     
	    //minDate : moment().millisecond(0).second(0).minute(0).hour(0),      
	  });
	$(".to_date").datetimepicker({      
	    format: 'MM-DD-YYYY',     
	    //minDate : moment().millisecond(0).second(0).minute(0).hour(0),      
	  });
	$(".button_print").click(function(){
		if($('input[name="check_id"]:checked').length > 0)
		{
			$("#form_print_checks").submit();
		}
		else
		{
			alert("None of the checkbox is selected.");
			return false;
		}
	});
</script>

app/views/admin/checks/create_payment_link.js.erb
$("#generated_link").html("<div class='row'><div class='form-group'><div class='col-md-6'><label>Copy and Paste Payment Link and send to the customer</label><br /><input type='text' style='width: 50%;' value='http://192.168.1.19:3000/payments/check/<%= @check.unique_code %>' class='form-control' /></div></div></div>")

app/views/admin/checks/edit.html.erb
<%= render "form" %>

app/views/admin/checks/index.html.erb
<% @main_title = "Print Check" %>
<% @span_title = "Search and Print check information" %>
<%= render "admin/shared/page_header" %>
<div class="page-container">
	<div class="page-content">
		<div class="content-wrapper">
			<%= render "layouts/flash_messages" %>
			<div class="panel panel-flat">
				<div class="panel-heading">
					<h5 class="panel-title">Checks</h5>
					<div class="heading-elements">
					</div>
				</div>
				<div class="panel-body">
					<%= render "search_checks_form" %>
					<div id="check_list">
						<%= render "check_list" %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/admin/checks/new.html.erb
<% @main_title = "Input Check" %>
<% @span_title = "Create new check information" %>
<%= render "admin/shared/page_header" %>
<div class="page-container">
	<div class="page-content">
		<div class="content-wrapper" ng-app="mainApp" ng-controller="checkController">
			<div class="panel panel-flat">
				<div class="panel-heading">
					<h5 class="panel-title">Enter Check Details</h5>
					<div class="heading-elements">

					</div>
				</div>	
				<div class="panel-body">
					<%= render "form" %>
				</div>
			</div>

			<div class="panel panel-flat">
				<div class="panel-body">
					<div class="row">
						<div class="cheque col-xs-12">
							<div class="cheque_content col-xs-12">
								<div class="col-xs-5 payee_detail text-left text-uppercase">
									<label class="col-xs-12 nopadding_lr">{{check.account_holder_name}}</label>
									<label class="col-xs-12 nopadding_lr">{{check.street_address}}</label>
									<label class="col-xs-12 nopadding_lr">{{check.fullAddress()}}</label>
								</div>

								<div class="col-xs-5 bank_detail text-center text-uppercase">
									<label class="col-xs-12 nopadding_lr"><strong>Wells Fargo Bank Na</strong></label>
									<label class="col-xs-12 nopadding_lr">Mac N9301-041</label>
									<label class="col-xs-12 nopadding_lr">Minneapolis Mn</label>
								</div>

								<div class="col-xs-2 cheque_number text-right">
									<label>{{check.check_number}}</label>
								</div>

								<div class="col-xs-12 cheque_date text-right">
									<label>{{check.date}}</label>
								</div>

								<div class="col-xs-12 nopadding_lr">
									<div class="col-xs-10 nopadding_lr check_amount_words">
										<label class="col-xs-2">
											Pay to the <br>
											Order of
										</label>

										<p class="col-xs-10">
											<strong>
												{{check.pay_to}}
											</strong>
										</p>

									</div>

									<div class="col-xs-2 check_amount text-right">
										<label class="col-xs-12">${{check.amount}}</label>
									</div>

									<div class="col-xs-12 check_amount_words">
										<p class="col-xs-11">
											<strong>Pay exactly ${{check.amount}} Dollors and Cents ///////////////////////////////</strong>
										</p>
									</div>
								</div>

								<div class="col-xs-12 nopadding_lr">
									<div class="col-xs-6 memo">
										<label class="col-xs-2">Memo</label>

										<div class="col-xs-10 nopadding_lr">
											<p class="col-xs-12 nopadding_lr">Customer authorization obtained: 04/04/2017</p>
											<p class="col-xs-12 nopadding_lr">{{check.memo1}}</p>
										</div>
									</div>

									<div class="col-xs-5 col-xs-offset-1 instruction nopadding_lr">
										<h4 class="col-xs-12 text-center text-uppercase">signature not required</h4>

										<p class="col-xs-12 nopadding_lr">Payment has been authorised by depositor.</p>
										<p class="col-xs-12 nopadding_lr">Payee to hold you harmless for payment of this document.</p>
										<p class="col-xs-12 nopadding_lr">This document shall be deposited only to credit of payee.</p>
										<p class="col-xs-12 nopadding_lr">Absence of endorsement is guaranteed by payee's bank.</p>
									</div>
								</div>

								<div class="col-xs-10 full_number">
									<label class="col-xs-4 text-center">c001031c</label>
									<label class="col-xs-4 text-center">a121042882a</label>
									<label class="col-xs-4 text-center">3141243976c</label>
								</div>

							</div>
						</div> 
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/admin/checks/payment_link.html.erb
<% @main_title = "Payment Link" %>
<% @span_title = "Generate Payment Link for Customer" %>
<%= render "admin/shared/page_header" %>

<div class="page-container">
	<div class="page-content">
		<div class="content-wrapper">
			<div class="panel panel-flat">
				<div class="panel-heading">
					<h5 class="panel-title">Enter Check Details</h5>
					<div class="heading-elements">
						<!-- <ul class="icons-list">
							<li><a data-action="collapse"></a></li>
							<li><a data-action="reload"></a></li>
							<li><a data-action="close"></a></li>
						</ul> -->
					</div>
				</div>

				<div class="panel-body">
					<%= form_tag create_payment_link_admin_checks_path, remote: true do %>
						<fieldset class="content-group">
					    <div class="row">
					      <div class="form-group">
					        <div class="col-md-6">
					          <%= text_field_tag "amount", "",autofocus: true, class: "form-control", placeholder: "Enter $ Amount or leave blank" %>
					        </div>
					      </div>
					    </div>
					    <br />
					    <div class="row">
					      <div class="form-group">
					        <div class="col-md-6">
					          <%= text_field_tag "transaction_fee", "", autofocus: true, class: "form-control", placeholder: "Enter Transaction Fee or leave blank" %>
					        </div>
					      </div>
					    </div>
					    <br />
					    <div class="row">
					      <div class="form-group">
					        <div class="col-md-6">
					          <%= check_box_tag "basic_verification", autofocus: true, class: "form-control" %>
					          Basic Verification
					        </div>
					      </div>
					    </div>
					    <br />
					    <div class="row">
					      <div class="form-group">
					        <div class="col-md-6">
					          <%= text_field_tag "memo", "", autofocus: true, class: "form-control", placeholder: "Memo" %>
					        </div>
					      </div>
					    </div>
					    <br />
					    <div class="row">
					      <div class="form-group">
					        <div class="col-md-6">
					          <%= text_field_tag "pay_to", "", autofocus: true, class: "form-control", placeholder: "Pay to the order of" %>
					        </div>
					      </div>
					    </div>
					    <br />
					    <div id="generated_link" %>
						    <div class="row">
						      <div class="form-group">
						        <div class="col-md-6">
						          <%= submit_tag "Generate Link", class: "btn btn-primary" %>
						        </div>
						      </div>
						    </div>
						  </div>
					  </fieldset>
					<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/admin/checks/search_check.js.erb
$("#check_list").html("<%= escape_javascript(render('check_list')) %>")