config/routes.rb
Rails.application.routes.draw do
  get 'payments/check/:id', to: "payments#check", as: :pay_check
  patch 'payments/update_check', to: "payments#update_check", as: :update_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root "home#index"
  get "/bettercheck", to: "home#bettercheck"
  namespace :admin do
    get "/dashboard", to: "dashboard#index", as: :dashboard
    get "/generate_check", to: "checks#generate_check", as: :generate_check, defaults: { format: 'pdf' }
    get "/change_password", to: "passwords#change_password", as: :change_password
    patch "/update_password", to: "passwords#update_password", as: :update_password
    resources :checks do
      collection do
        post "/search_check", to: "checks#search_check"
        get "/payment_link", to: "checks#payment_link"
        post "/create_payment_link", to: "checks#create_payment_link"
      end
    end
    get "/reports", to: "reports#index", as: :reports
    resources :subscriptions
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def check
  	@check = Check.find_by_unique_code(params[:id])
  end

  def update_check
  	@check = Check.find(params[:check][:id])
  	@check.update(check_params)
  	if @check.save
  		redirect_to root_path, success: "You have updated check details."
  	else
  		render :check, notice: @check.errors.full_messages
  	end
  end

  private
	def check_params
    params.require(:check).permit(:account_holder_name, :street_address, :city, :state, :zip, :date, :check_number, :pay_to_the_order_of, :amount, :memo1, :memo2, :routing_number, :checking_account_number)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/check.html.erb
<%= form_for(@check, url: update_check_path) do |f| %>
  <%= f.hidden_field :id %>
	<div class="field">
    <%= f.label :account_holder_name %><br />
    <%= f.text_field :account_holder_name, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_field :date, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :check_number %><br />
    <%= f.text_field :check_number, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :pay_to_the_order_of %><br />
    <%= f.text_field :pay_to_the_order_of, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :memo1 %><br />
    <%= f.text_field :memo1, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :memo2 %><br />
    <%= f.text_field :memo2, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :routing_number %><br />
    <%= f.text_field :routing_number, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :checking_account_number %><br />
    <%= f.text_field :checking_account_number, autofocus: true %>
  </div>
  <div class="actions">
  	<% if f.object.new_record? %>
    	<%= f.submit "Create" %>
    <% else %>
    	<%= f.submit "Update" %>
    <% end %>
  </div>
<% end %>